version: '3.3'

services:
  app:
    build:
      context: .
    ports:      
      - '3000:3000'
    volumes:
      - .:/app
    depends_on: 
      - db      
  

  db:
    image: mysql:5.6
    ports:
      - '3306:3306'
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gaivota  
  

      